import type { Post, User, Interest, Comment, Notification, Tag } from '@/types';

// ─── Mock Users ───────────────────────────────────────────
export const MOCK_USERS: User[] = [
    {
        id: 'u1', email: 'sofia@inkboard.eu', username: 'sofia_writes',
        display_name: 'Sofia Andersson', bio: 'Swedish novelist & travel essayist. Writing about Scandinavia, language, and the human condition. Stockholm-based.',
        avatar_url: 'https://i.pravatar.cc/150?img=47', location: 'Stockholm, Sweden',
        role: 'USER', is_verified: true, is_suspended: false, is_business: false, created_at: '2026-01-05T10:00:00Z',
        follower_count: 3420, following_count: 218, total_likes: 18450, post_count: 34,
    },
    {
        id: 'u2', email: 'marco@inkboard.eu', username: 'marco_romano',
        display_name: 'Marco Romano', bio: 'Food journalist & culture critic. Rome → Berlin. Writing about gastronomy, identity, and Mediterranean life.',
        avatar_url: 'https://i.pravatar.cc/150?img=12', location: 'Berlin, Germany',
        role: 'USER', is_verified: true, is_suspended: false, is_business: false, created_at: '2026-01-08T14:00:00Z',
        follower_count: 5120, following_count: 340, total_likes: 29800, post_count: 67,
    },
    {
        id: 'u3', email: 'elise@inkboard.eu', username: 'elise_page',
        display_name: 'Élise Dupont', bio: 'Literary fiction & poetry. Paris-based writer & editor at Revue de lucioles. Lover of Proust and long walks.',
        avatar_url: 'https://i.pravatar.cc/150?img=25', location: 'Paris, France',
        role: 'USER', is_verified: true, is_suspended: false, is_business: false, created_at: '2026-01-12T09:00:00Z',
        follower_count: 8900, following_count: 125, total_likes: 54200, post_count: 112,
    },
    {
        id: 'u4', email: 'kai@inkboard.eu', username: 'kai_nordhavn',
        display_name: 'Kai Nordhavn', bio: 'Tech journalist & essayist. Writing about AI, ethics, and digital culture from Copenhagen.',
        avatar_url: 'https://i.pravatar.cc/150?img=52', location: 'Copenhagen, Denmark',
        role: 'USER', is_verified: false, is_suspended: false, is_business: false, created_at: '2026-01-18T16:00:00Z',
        follower_count: 1800, following_count: 450, total_likes: 9400, post_count: 21,
    },
    {
        id: 'u5', email: 'amara@inkboard.eu', username: 'amara_adeola',
        display_name: 'Amara Adeola', bio: 'Nigerian-British novelist. Shortlisted for the Booker. Writing about diaspora, memory, and belonging. Based in London.',
        avatar_url: 'https://i.pravatar.cc/150?img=56', location: 'London, UK',
        role: 'USER', is_verified: true, is_suspended: false, is_business: false, created_at: '2026-01-20T11:00:00Z',
        follower_count: 12400, following_count: 87, total_likes: 98200, post_count: 45,
    },
];

// ─── Mock Tags ────────────────────────────────────────────
export const MOCK_TAGS: Tag[] = [
    { id: 't1', name: 'literature', post_count: 2840 },
    { id: 't2', name: 'travel', post_count: 1920 },
    { id: 't3', name: 'philosophy', post_count: 1340 },
    { id: 't4', name: 'food', post_count: 980 },
    { id: 't5', name: 'tech', post_count: 2100 },
    { id: 't6', name: 'poetry', post_count: 760 },
    { id: 't7', name: 'culture', post_count: 1560 },
    { id: 't8', name: 'politics', post_count: 1200 },
    { id: 't9', name: 'health', post_count: 890 },
    { id: 't10', name: 'fiction', post_count: 1430 },
    { id: 't11', name: 'photography', post_count: 640 },
    { id: 't12', name: 'environment', post_count: 710 },
];

// ─── Mock Posts ───────────────────────────────────────────
export const MOCK_POSTS: Post[] = [
    {
        id: 'p1', author_id: 'u3', author: MOCK_USERS[2],
        title: 'The Silence Between Words: On Proust and the Art of Slow Reading',
        subtitle: 'Why Proust demands not just time, but a complete recalibration of how we encounter language.',
        cover_image_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80',
        cover_aspect_ratio: '2:3',
        status: 'PUBLISHED', read_time_minutes: 9, engagement_score: 2840.5,
        like_count: 1240, comment_count: 87, share_count: 203, is_trending: true,
        tags: [MOCK_TAGS[0], MOCK_TAGS[5], MOCK_TAGS[6]],
        created_at: '2026-02-20T10:00:00Z', published_at: '2026-02-20T10:00:00Z',
        content: '<p>Marcel Proust\'s <em>In Search of Lost Time</em> occupies a peculiar position in literary culture...</p>',
    },
    {
        id: 'p2', author_id: 'u2', author: MOCK_USERS[1],
        title: 'Carbonara Is Not What You Think It Is',
        subtitle: 'A deep dive into the mythology, politics, and perfect technique of Rome\'s most contested dish.',
        cover_image_url: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80',
        cover_aspect_ratio: '4:3',
        status: 'PUBLISHED', read_time_minutes: 6, engagement_score: 3120.8,
        like_count: 1890, comment_count: 134, share_count: 445, is_trending: true,
        tags: [MOCK_TAGS[3], MOCK_TAGS[6]],
        created_at: '2026-02-21T12:00:00Z', published_at: '2026-02-21T12:00:00Z',
        content: '<p>Ask any Roman nonna and she will tell you that the only acceptable carbonara guanciale is...</p>',
    },
    {
        id: 'p3', author_id: 'u1', author: MOCK_USERS[0],
        title: 'Midnight in Lapland: Following the Northern Lights Into Silence',
        subtitle: 'Three weeks alone in the Finnish wilderness taught me something about time that no book could.',
        cover_image_url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80',
        cover_aspect_ratio: '9:16',
        status: 'PUBLISHED', read_time_minutes: 12, engagement_score: 1980.2,
        like_count: 920, comment_count: 56, share_count: 178, is_trending: false,
        tags: [MOCK_TAGS[1], MOCK_TAGS[6]],
        created_at: '2026-02-19T08:00:00Z', published_at: '2026-02-19T08:00:00Z',
        content: '<p>The first rule of aurora hunting is patience. The second rule is more patience...</p>',
    },
    {
        id: 'p4', author_id: 'u4', author: MOCK_USERS[3],
        title: 'When the Algorithm Became the Editor',
        subtitle: 'With AI writing tools flooding the internet, what happens to the editorial voice?',
        cover_image_url: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80',
        cover_aspect_ratio: '16:9',
        status: 'PUBLISHED', read_time_minutes: 8, engagement_score: 2200.1,
        like_count: 760, comment_count: 98, share_count: 320, is_trending: true,
        tags: [MOCK_TAGS[4], MOCK_TAGS[2], MOCK_TAGS[7]],
        created_at: '2026-02-22T14:00:00Z', published_at: '2026-02-22T14:00:00Z',
        content: '<p>In 2023, a major European literary magazine published a short story generated by an AI...</p>',
    },
    {
        id: 'p5', author_id: 'u5', author: MOCK_USERS[4],
        title: 'Between Two Worlds: A Memoir Fragment',
        subtitle: 'On the impossible geography of belonging when you are made of two homelands.',
        cover_image_url: 'https://images.unsplash.com/photo-1510936111840-65e151ad71bb?w=600&q=80',
        cover_aspect_ratio: '3:4',
        status: 'PUBLISHED', read_time_minutes: 14, engagement_score: 4560.9,
        like_count: 2340, comment_count: 189, share_count: 612, is_trending: true,
        tags: [MOCK_TAGS[9], MOCK_TAGS[0], MOCK_TAGS[6]],
        created_at: '2026-02-23T09:00:00Z', published_at: '2026-02-23T09:00:00Z',
        content: '<p>My mother always said that I spoke Yoruba like a child who learned it from a book...</p>',
    },
    {
        id: 'p6', author_id: 'u1', author: MOCK_USERS[0],
        title: 'On the Swedish Concept of Lagom and Why the World Needs It Now',
        subtitle: '"Not too much, not too little" — a philosophy for an era of extremes.',
        cover_image_url: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=600&q=80',
        cover_aspect_ratio: '1:1',
        status: 'PUBLISHED', read_time_minutes: 5, engagement_score: 1540.3,
        like_count: 680, comment_count: 45, share_count: 230, is_trending: false,
        tags: [MOCK_TAGS[2], MOCK_TAGS[6]],
        created_at: '2026-02-18T11:00:00Z', published_at: '2026-02-18T11:00:00Z',
        content: '<p>There is a Swedish word that has no direct translation in English: lagom...</p>',
    },
    {
        id: 'p7', author_id: 'u3', author: MOCK_USERS[2],
        title: 'Simone de Beauvoir\'s Paris: A Walking Guide to Existentialist Haunts',
        subtitle: 'From Café de Flore to the grave at Montparnasse — tracing a philosophy through streets.',
        cover_image_url: 'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=600&q=80',
        cover_aspect_ratio: '16:9',
        status: 'PUBLISHED', read_time_minutes: 7, engagement_score: 2100.6,
        like_count: 1120, comment_count: 72, share_count: 290, is_trending: false,
        tags: [MOCK_TAGS[1], MOCK_TAGS[2], MOCK_TAGS[0]],
        created_at: '2026-02-17T15:00:00Z', published_at: '2026-02-17T15:00:00Z',
        content: '<p>Begin at Café de Flore on the Boulevard Saint-Germain at 8am, when the light...</p>',
    },
    {
        id: 'p8', author_id: 'u2', author: MOCK_USERS[1],
        title: 'The Italian Aperitivo: A Ceremony of Pleasure',
        subtitle: 'Why the hour between 6 and 8pm is the most civilised institution in human history.',
        cover_image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80',
        cover_aspect_ratio: '4:3',
        status: 'PUBLISHED', read_time_minutes: 5, engagement_score: 1890.4,
        like_count: 980, comment_count: 63, share_count: 340, is_trending: false,
        tags: [MOCK_TAGS[3], MOCK_TAGS[6], MOCK_TAGS[1]],
        created_at: '2026-02-16T18:00:00Z', published_at: '2026-02-16T18:00:00Z',
        content: '<p>There is a precise moment in every Italian city when the streets change character...</p>',
    },
    {
        id: 'p9', author_id: 'u4', author: MOCK_USERS[3],
        title: 'The Copenhagen School of Design: Why Function Is Never Enough',
        subtitle: 'Danish design philosophy goes far beyond clean lines — it is a moral position.',
        cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
        cover_aspect_ratio: '3:4',
        status: 'PUBLISHED', read_time_minutes: 8, engagement_score: 1320.7,
        like_count: 540, comment_count: 38, share_count: 120, is_trending: false,
        tags: [MOCK_TAGS[6], MOCK_TAGS[4]],
        created_at: '2026-02-15T10:00:00Z', published_at: '2026-02-15T10:00:00Z',
        content: '<p>Arne Jacobsen once said that a chair should do more than merely hold a body...</p>',
    },
    {
        id: 'p10', author_id: 'u5', author: MOCK_USERS[4],
        title: 'On Grief and the Novel: How Fiction Helps Us Carry Sorrow',
        subtitle: 'A meditation on how writers from Woolf to Achebe have made grief into literature.',
        cover_image_url: 'https://images.unsplash.com/photo-1476234251651-f353703a034d?w=600&q=80',
        cover_aspect_ratio: '2:3',
        status: 'PUBLISHED', read_time_minutes: 11, engagement_score: 3200.1,
        like_count: 1560, comment_count: 142, share_count: 480, is_trending: true,
        tags: [MOCK_TAGS[0], MOCK_TAGS[9], MOCK_TAGS[2]],
        created_at: '2026-02-24T07:00:00Z', published_at: '2026-02-24T07:00:00Z',
        content: '<p>When my father died, I could not cry. I read instead. I consumed novels...</p>',
    },
    {
        id: 'p11', author_id: 'u2', author: MOCK_USERS[1],
        title: 'The Rebirth of European Sourdough: Beyond the Instagram Loaf',
        subtitle: 'A journey through Berlin\'s wheat revolution — where ancient grains meet the modern kitchen.',
        cover_image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
        cover_aspect_ratio: '1:1',
        status: 'PUBLISHED', read_time_minutes: 6, engagement_score: 1780.5,
        like_count: 820, comment_count: 47, share_count: 210, is_trending: false,
        tags: [MOCK_TAGS[3], MOCK_TAGS[6]],
        created_at: '2026-02-14T09:00:00Z', published_at: '2026-02-14T09:00:00Z',
        content: '<p>The bakery on Kastanienallee opens at 7am but the queue starts forming at half six...</p>',
    },
    {
        id: 'p12', author_id: 'u3', author: MOCK_USERS[2],
        title: 'Poetry in the Age of the Feed',
        subtitle: 'How poets are adapting to short attention spans, and whether we should resist.',
        cover_image_url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80',
        cover_aspect_ratio: '9:16',
        status: 'PUBLISHED', read_time_minutes: 4, engagement_score: 1420.3,
        like_count: 640, comment_count: 55, share_count: 190, is_trending: false,
        tags: [MOCK_TAGS[5], MOCK_TAGS[0], MOCK_TAGS[4]],
        created_at: '2026-02-13T13:00:00Z', published_at: '2026-02-13T13:00:00Z',
        content: '<p>The poem arrived in my notifications between an advertisement and a repost...</p>',
    },
];

// ─── Mock Interests ───────────────────────────────────────
export const MOCK_INTERESTS: Interest[] = [
    { id: 'i1', name: 'Literature', icon: '📚', category: 'Arts' },
    { id: 'i2', name: 'Travel', icon: '✈️', category: 'Lifestyle' },
    { id: 'i3', name: 'Technology', icon: '💻', category: 'Tech' },
    { id: 'i4', name: 'Food & Drink', icon: '🍽️', category: 'Lifestyle' },
    { id: 'i5', name: 'Politics', icon: '🏛️', category: 'Society' },
    { id: 'i6', name: 'Philosophy', icon: '🧠', category: 'Arts' },
    { id: 'i7', name: 'Poetry', icon: '✍️', category: 'Arts' },
    { id: 'i8', name: 'Health & Wellness', icon: '🌿', category: 'Lifestyle' },
    { id: 'i9', name: 'Photography', icon: '📷', category: 'Arts' },
    { id: 'i10', name: 'Music', icon: '🎵', category: 'Arts' },
    { id: 'i11', name: 'Cinema', icon: '🎬', category: 'Arts' },
    { id: 'i12', name: 'Science', icon: '🔬', category: 'Science' },
    { id: 'i13', name: 'Environment', icon: '🌍', category: 'Society' },
    { id: 'i14', name: 'Economics', icon: '📈', category: 'Society' },
    { id: 'i15', name: 'Architecture', icon: '🏛️', category: 'Arts' },
    { id: 'i16', name: 'History', icon: '📜', category: 'Society' },
    { id: 'i17', name: 'Culture', icon: '🎭', category: 'Arts' },
    { id: 'i18', name: 'Fashion', icon: '👗', category: 'Lifestyle' },
    { id: 'i19', name: 'Psychology', icon: '🧬', category: 'Science' },
    { id: 'i20', name: 'Fiction', icon: '📖', category: 'Arts' },
    { id: 'i21', name: 'Journalism', icon: '📰', category: 'Society' },
    { id: 'i22', name: 'Parenting', icon: '👨‍👩‍👧', category: 'Lifestyle' },
    { id: 'i23', name: 'Sports', icon: '⚽', category: 'Lifestyle' },
    { id: 'i24', name: 'Gaming', icon: '🎮', category: 'Tech' },
    { id: 'i25', name: 'AI & Ethics', icon: '🤖', category: 'Tech' },
    { id: 'i26', name: 'Law', icon: '⚖️', category: 'Society' },
    { id: 'i27', name: 'Art & Design', icon: '🎨', category: 'Arts' },
    { id: 'i28', name: 'Language', icon: '🗣️', category: 'Society' },
    { id: 'i29', name: 'Nature', icon: '🌲', category: 'Lifestyle' },
    { id: 'i30', name: 'Spirituality', icon: '✨', category: 'Lifestyle' },
];

// ─── Mock Notifications ───────────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
    {
        id: 'n1', type: 'LIKE', actor: MOCK_USERS[1],
        entity_type: 'POST', entity_id: 'p1', is_read: false,
        created_at: '2026-02-25T11:30:00Z',
        post_title: 'The Silence Between Words: On Proust and the Art of Slow Reading',
    },
    {
        id: 'n2', type: 'COMMENT', actor: MOCK_USERS[3],
        entity_type: 'POST', entity_id: 'p1', is_read: false,
        created_at: '2026-02-25T10:15:00Z',
        post_title: 'The Silence Between Words: On Proust and the Art of Slow Reading',
    },
    {
        id: 'n3', type: 'FOLLOW', actor: MOCK_USERS[4],
        entity_type: 'POST', entity_id: '', is_read: false,
        created_at: '2026-02-25T09:00:00Z',
    },
    {
        id: 'n4', type: 'TRENDING', actor: MOCK_USERS[0],
        entity_type: 'POST', entity_id: 'p3', is_read: true,
        created_at: '2026-02-24T18:00:00Z',
        post_title: 'Midnight in Lapland: Following the Northern Lights Into Silence',
    },
    {
        id: 'n5', type: 'REPLY', actor: MOCK_USERS[0],
        entity_type: 'COMMENT', entity_id: 'c1', is_read: true,
        created_at: '2026-02-24T15:00:00Z',
        post_title: 'Simone de Beauvoir\'s Paris',
    },
];

// ─── Mock Comments ────────────────────────────────────────
export const getMockComments = (postId: string): Comment[] => [
    {
        id: 'c1', post_id: postId, author: MOCK_USERS[1],
        content: 'This is one of the most beautifully written pieces I\'ve read all year. The way you describe the silence between sentences — it\'s like you\'ve articulated something I could feel but never name.',
        is_hidden: false, created_at: '2026-02-20T14:30:00Z',
        replies: [
            {
                id: 'c1r1', post_id: postId, author: MOCK_USERS[2],
                parent_comment_id: 'c1',
                content: 'Thank you so much, Marco. That means a great deal coming from you.',
                is_hidden: false, created_at: '2026-02-20T15:00:00Z',
            },
        ],
    },
    {
        id: 'c2', post_id: postId, author: MOCK_USERS[3],
        content: 'I\'ve been putting off reading Proust for years. This might be the push I needed. Starting with Swann\'s Way tomorrow.',
        is_hidden: false, created_at: '2026-02-21T09:00:00Z',
        replies: [],
    },
    {
        id: 'c3', post_id: postId, author: MOCK_USERS[4],
        content: 'Your point about the act of re-reading as an alternative mode of time resonates deeply with me. It\'s what I felt rereading Achebe\'s Arrow of God last month.',
        is_hidden: false, created_at: '2026-02-21T11:30:00Z',
        replies: [],
    },
];
